apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: mindlease-ma-tls
spec:
  secretName: mindlease-ma
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: mindlease.ma
  dnsNames:
    - mindlease.ma
    - www.mindlease.ma
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - mindlease.ma
          - www.mindlease.ma